/*
 * main.c
 *
 *  Created on: Oct 12, 2022
 *      Author: mustafa
 */
#include "lcd.h"
#include "std_types.h"
#include "ultrasonic_sensor.h"
#include <avr/io.h> /* To use the SREG register */
#include "icu.h"



/*Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.*/
extern uint16 Edge_Count;
extern uint16 Time;

void Ultrasonic_edgeProcessing(void)
{
	Edge_Count++;
	if(Edge_Count == 1)
	{
		Icu_clearTimerValue();
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(Edge_Count == 2)
	{
		Time=Icu_getInputCaptureValue();
		Icu_setEdgeDetectionType(RAISING);
		Icu_clearTimerValue();
		Edge_Count=0;
	}
}

int main(void)
{
	uint16 distance=0;
	/* Enable Global Interrupt I-Bit */
	SREG |= (1<<7);
	LCD_init();
	Ultrasonic_init();
	//Displaying
	LCD_displayString("Distance =    cm");
	while(1)
	{
		distance=Ultrasonic_readDistance();
		if(distance>=400)
		{
			LCD_moveCursor(0,11);
			LCD_intgerToString(400);
			LCD_moveCursor(2,7);
			LCD_displayString("MAX");
		}
		else if(distance >= 100)
		{
			LCD_moveCursor(0,11);
			LCD_intgerToString(distance);
			LCD_moveCursor(2,7);
			LCD_displayString("   ");
		}
		else
		{
			LCD_moveCursor(0,11);
			LCD_intgerToString(distance);
			/* In case the digital value is two or one digits print space in the next digit place */
			LCD_displayCharacter(' ');
			LCD_moveCursor(2,7);
			LCD_displayString("   ");
		}
	}
}
